spring.application.name=backend
jwt.jwtSecret=Z3JlZW5iYWNrLXNlY3VyZS1qd3Qtc2VjcmV0LWtleS0yMDI2LTAzLTI2
jwt.jwtExpirationMs=86400000
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
spring.datasource.url=jdbc:postgresql://localhost:5432/Construction
spring.datasource.username=postgres
server.port=8085
spring.datasource.password=laure
spring.datasource.driver-class-name=org.postgresql.Driver
 
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.frontend-url=${FRONTEND_URL:http://localhost:4200}
app.mail.from=${MAIL_FROM:no-reply@archimorph.local}

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=e05fc570bac9ef
spring.mail.password=7345da2d868188
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
